### ISSUE TITLE
Shift-reduce parser missing

### ISSUE THREAD

**Issue by f0lie** [vzhong/corenlp-docker#1] opened 2017-07-19 20:09 UTC
Hello,

I pulled from docker-hub and ran the container.

I got this from the start:
```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 9
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP - using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
[main] INFO CoreNLP - to use shift reduce parser download English models jar from:
[main] INFO CoreNLP - http://stanfordnlp.github.io/CoreNLP/download.html
[main] INFO CoreNLP -     Threads: 4
[main] INFO CoreNLP - Starting server...
[main] INFO CoreNLP - StanfordCoreNLPServer listening at /0.0.0.0:9000
```

While `englishPCFG.ser.gz` works fine, `englishSR.ser.gz` is faster for [longer sentences](https://stanfordnlp.github.io/CoreNLP/memory-time.html#depparse).

Thanks,

**Comment by vzhong** [comment] 2017-08-07 17:43
Hi @f0lie, this seems like a CoreNLP issue (https://github.com/stanfordnlp/CoreNLP). Do you also see it with normal Java CoreNLP?

**Comment by vzhong** [comment] 2017-08-07 17:44
This is definitely not a bug. From CoreNLP's README:

> Some of the larger (English) models -- like the shift-reduce parser and WikiDict -- are not distributed with our default models jar. The most recent version of these models can be found here.

Closing this issue.

**Closed by vzhong** 2017-08-07 17:44 UTC
